"""pred-demo — embarrassment arm: naive direction invents held on wrong magnitude.

Found 2026-09-11 by running:
  check_prediction("pass rate rises by 2/5", "helped", 1) → prediction-held

That was a lie. Magnet now checks the claimed fraction; the old behaviour
ships as the naive arm so a stranger can see us lose to honesty.

Slice 28: stay-at without /pop, remain/hold lexicon, floor claims.

Slice 32: recover/restore rise lexicon — Devpost one-workflow prediction
`pass rate recovers by 1` must grade, not print no-direction.

Slice 35: negation (`won't fall` was fall — invents held on drop), ceiling
(`at most 3/5`), target-level (`falls to 2/5` grades latest).
"""
from __future__ import annotations

from dataclasses import dataclass

from magnet.prediction import (
    check_prediction,
    claimed_ceiling,
    claimed_floor,
    claimed_level,
    claimed_magnitude,
    claimed_percent,
    claimed_ratio,
    claimed_target,
    naive_direction_check,
    prediction_intent,
)


@dataclass(frozen=True)
class PredScenario:
    name: str
    prediction: str
    label: str
    delta: int | None
    population: int | None
    magnet_truth: str
    latest_value: int | None = None
    note: str = ""


# Ground truth is magnet's magnitude/level-aware grade. Naive is scored against the
# same truth so a direction-only hold on a wrong fraction/level counts as a naive win
# that we refuse — the embarrassment.
SCENARIOS: tuple[PredScenario, ...] = (
    PredScenario(
        "correct_fraction",
        "pass rate rises by 1/5",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="claim matches measured Δ +1 on pop 5",
    ),
    PredScenario(
        "wrong_magnitude",
        "pass rate rises by 2/5",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="direction ok but claimed Δ +2 ≠ measured +1 — THE LIE Slice 24 printed held",
    ),
    PredScenario(
        "wrong_population",
        "coverage rises by 1/5",
        "helped",
        1,
        12,
        "prediction-missed",
        latest_value=9,
        note="Δ matches but claimed pop 5 ≠ measured 12",
    ),
    PredScenario(
        "vague_rise",
        "coverage rises",
        "helped",
        1,
        12,
        "prediction-held",
        latest_value=9,
        note="no fraction claimed — direction is the whole grade",
    ),
    PredScenario(
        "strip_fall",
        "simplify skill frontmatter",
        "hurt",
        -7,
        7,
        "prediction-held",
        latest_value=0,
        note="fall intent, no fraction — foreign-hurt titles still grade",
    ),
    PredScenario(
        "still_pass_flat",
        "all tests still pass",
        "unchanged",
        0,
        190,
        "prediction-held",
        latest_value=190,
        note="still pass → flat; judge-demo prediction becomes checkable",
    ),
    PredScenario(
        "still_pass_missed",
        "all tests still pass",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="claimed flat, measured helped",
    ),
    PredScenario(
        "fall_fraction",
        "pass rate falls by 2/5",
        "hurt",
        -2,
        5,
        "prediction-held",
        latest_value=2,
        note="fall + matching magnitude",
    ),
    PredScenario(
        "stay_at_holds",
        "must stay at 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="stay-at level matches latest 4/5",
    ),
    PredScenario(
        "stay_at_wrong_level",
        "must stay at 5/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="flat ok but latest 4 ≠ claimed 5 — THE LIE Slice 25 left open",
    ),
    PredScenario(
        "stay_at_no_slash",
        "must stay at 5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="no /pop — Slice 26 left unparsed → invents held; now grades value",
    ),
    PredScenario(
        "remain_at_wrong",
        "must remain at 5/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="remain-at was no-direction while level sat on the table",
    ),
    PredScenario(
        "hold_at_wrong",
        "hold at 190/190",
        "unchanged",
        0,
        190,
        "prediction-missed",
        latest_value=189,
        note="hold-at lexicon; latest 189 ≠ claimed 190",
    ),
    PredScenario(
        "floor_holds",
        "pass rate at least 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="floor met: latest 4 ≥ claimed 4",
    ),
    PredScenario(
        "floor_missed",
        "pass rate at least 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="direction flat ok but latest 3 < floor 4 — naive invents held",
    ),
    PredScenario(
        "recover_held",
        "pass rate recovers by 1",
        "helped",
        1,
        244,
        "prediction-held",
        latest_value=244,
        note="DEMO-ONE-WORKFLOW restore step — was no-direction before Slice 32",
    ),
    PredScenario(
        "recover_wrong_mag",
        "pass rate recovers by 2",
        "helped",
        1,
        244,
        "prediction-missed",
        latest_value=244,
        note="recover is rise; claimed Δ +2 ≠ measured +1 — magnitude still bites",
    ),
    PredScenario(
        "restore_held",
        "coverage restores by 1",
        "helped",
        1,
        12,
        "prediction-held",
        latest_value=9,
        note="restore lexicon grades as rise with matching magnitude",
    ),
    PredScenario(
        "wont_fall_holds",
        "pass rate won't fall",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="negation → flat; unchanged holds — THE LIE was fall→missed",
    ),
    PredScenario(
        "wont_fall_missed",
        "pass rate won't fall",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: old magnet graded won't-fall as fall → invents held on drop",
    ),
    PredScenario(
        "does_not_regress_holds",
        "coverage does not regress",
        "unchanged",
        0,
        12,
        "prediction-held",
        latest_value=9,
        note="does not regress → flat, not fall",
    ),
    PredScenario(
        "ceiling_holds",
        "pass rate at most 3/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=3,
        note="ceiling met: latest 3 ≤ claimed 3",
    ),
    PredScenario(
        "ceiling_missed",
        "pass rate at most 3/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="latest 4 > ceiling 3 — naive invents held on flat direction",
    ),
    PredScenario(
        "falls_to_holds",
        "pass rate falls to 2/5",
        "hurt",
        -2,
        5,
        "prediction-held",
        latest_value=2,
        note="fall + target 2/5 matches latest",
    ),
    PredScenario(
        "falls_to_missed",
        "pass rate falls to 2/5",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=3,
        note="direction fall ok but latest 3 ≠ target 2 — THE LIE was held",
    ),
    PredScenario(
        "reaches_holds",
        "pass rate reaches 5/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="target-only reaches grades latest == 5",
    ),
    PredScenario(
        "reaches_missed",
        "pass rate reaches 5/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="reaches 5 with latest 4 — was no-direction before Slice 35",
    ),
    PredScenario(
        "improves_held",
        "coverage improves by 1",
        "helped",
        1,
        12,
        "prediction-held",
        latest_value=9,
        note="improves was unknown (improv stem word-boundary fail) — now rise",
    ),
    PredScenario(
        "percent_of_pop_holds",
        "coverage improves by 20%",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="20% of pop 5 = Δ+1 — THE LIE treated % as absolute 20 and missed",
    ),
    PredScenario(
        "percent_absolute_lie",
        "coverage improves by 20%",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="Δ+20 on pop 5 is not 20% — old magnet invented held by stripping %",
    ),
    PredScenario(
        "exactly_holds",
        "must be exactly 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="exactly 4/5 grades latest == 4",
    ),
    PredScenario(
        "exactly_missed",
        "exactly 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="exactly 4 with latest 3 — was no-direction; naive flat invents held",
    ),
    PredScenario(
        "doubles_holds",
        "pass rate doubles",
        "helped",
        2,
        5,
        "prediction-held",
        latest_value=4,
        note="prior=2 → doubles to 4; Δ == prior",
    ),
    PredScenario(
        "doubles_missed",
        "pass rate doubles",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="prior=3 → not a double; direction-only invents held — THE LIE",
    ),
    PredScenario(
        "halves_holds",
        "pass rate halves",
        "hurt",
        -2,
        5,
        "prediction-held",
        latest_value=2,
        note="prior=4 → halves to 2",
    ),
    PredScenario(
        "halves_missed",
        "pass rate halves",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=3,
        note="prior=4 → not a half; direction fall invents held",
    ),
    PredScenario(
        "wont_fall_below_holds",
        "won't fall below 3/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="below-bound floor met: latest 4 ≥ 3",
    ),
    PredScenario(
        "wont_fall_below_missed",
        "won't fall below 3/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=2,
        note="THE LIE: floor unbound → invented held at latest 2; now misses",
    ),
    PredScenario(
        "stays_above_holds",
        "stays above 3/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="exclusive above: latest 4 > 3",
    ),
    PredScenario(
        "stays_above_missed",
        "stays above 3/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="latest 3 is not above 3; naive flat invents held",
    ),
    PredScenario(
        "no_lower_than_holds",
        "no lower than 3/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=3,
        note="no lower than was intent=fall; now flat+floor",
    ),
    PredScenario(
        "rises_pct_no_by_holds",
        "rises 20%",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 39: rises 20% without by — was unbound direction-only",
    ),
    PredScenario(
        "rises_pct_no_by_missed",
        "rises 20%",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE: unbound % invented held on absolute-sized Δ+20",
    ),
    PredScenario(
        "triples_holds",
        "pass rate triples",
        "helped",
        4,
        10,
        "prediction-held",
        latest_value=6,
        note="prior=2 → triples to 6",
    ),
    PredScenario(
        "triples_missed",
        "pass rate triples",
        "helped",
        1,
        10,
        "prediction-missed",
        latest_value=4,
        note="prior=3 → not a triple; direction invents held",
    ),
    PredScenario(
        "three_x_holds",
        "3x",
        "helped",
        4,
        10,
        "prediction-held",
        latest_value=6,
        note="3x ≡ triple",
    ),
    PredScenario(
        "word_percent_holds",
        "improves by 20 percent",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 40: word percent ≡ % — true 20% of pop 5 is Δ=+1",
    ),
    PredScenario(
        "word_percent_missed",
        "improves by 20 percent",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE: word percent was absolute amount=20 → invented held on Δ=+20",
    ),
    PredScenario(
        "never_falls_flat_holds",
        "never falls",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=3,
        note="Slice 40: never falls is flat, not fall",
    ),
    PredScenario(
        "never_falls_hurt_missed",
        "never falls",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=2,
        note="THE LIE: never falls was fall → invented held when score dropped",
    ),
    PredScenario(
        "wont_decrease_hurt_missed",
        "won't decrease",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=2,
        note="won't decrease was fall (decrease in fall lexicon, not in negation)",
    ),
    PredScenario(
        "cannot_fall_flat_holds",
        "cannot fall",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="cannot fall → flat",
    ),
    PredScenario(
        "falls_to_zero_holds",
        "falls to zero",
        "hurt",
        -3,
        5,
        "prediction-held",
        latest_value=0,
        note="Slice 41: zero ≡ 0 target",
    ),
    PredScenario(
        "falls_to_zero_missed",
        "falls to zero",
        "hurt",
        -2,
        5,
        "prediction-missed",
        latest_value=1,
        note="THE LIE: zero unbound → direction invented held at latest=1",
    ),
    PredScenario(
        "goes_to_zero_holds",
        "goes to zero",
        "hurt",
        -4,
        5,
        "prediction-held",
        latest_value=0,
        note="goes to opens target; flat intent grades latest only",
    ),
    PredScenario(
        "perfect_holds",
        "perfect 5/5",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=5,
        note="perfect N/N is a target",
    ),
    PredScenario(
        "perfect_missed",
        "perfect 5/5",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="perfect unbound was no-direction; now misses wrong latest",
    ),
    PredScenario(
        "quadruples_holds",
        "pass rate quadruples",
        "helped",
        6,
        10,
        "prediction-held",
        latest_value=8,
        note="prior=2 → quadruples to 8",
    ),
    PredScenario(
        "quadruples_missed",
        "pass rate quadruples",
        "helped",
        1,
        10,
        "prediction-missed",
        latest_value=4,
        note="not a quadruple; direction invents held",
    ),
    PredScenario(
        "five_times_holds",
        "five times",
        "helped",
        4,
        10,
        "prediction-held",
        latest_value=5,
        note="prior=1 → five times = 5",
    ),
    PredScenario(
        "five_times_missed",
        "five times",
        "helped",
        1,
        10,
        "prediction-missed",
        latest_value=3,
        note="N times was unbound; direction invents held",
    ),
    PredScenario(
        "pct_better_holds",
        "50% better",
        "helped",
        2,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 42: 50% better ≡ 50% of pop (Δ=+2 on pop 5)",
    ),
    PredScenario(
        "pct_better_missed",
        "50% better",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE risk: unbound better left no-direction; direction invents held on absolute Δ",
    ),
    PredScenario(
        "pct_worse_holds",
        "50% worse",
        "hurt",
        -2,
        5,
        "prediction-held",
        latest_value=1,
        note="50% worse → fall + percent",
    ),
    PredScenario(
        "gains_pct_holds",
        "gains 20%",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="gains/jumps/boosts were unknown even when % parsed",
    ),
    PredScenario(
        "gains_pct_missed",
        "gains 20%",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="direction invents held on absolute-sized gain",
    ),
    PredScenario(
        "boosts_by_pct_missed",
        "boosts by 20%",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=5,
        note="pct parsed but intent unknown → no-direction; now rise+percent misses abs",
    ),
    # Slice 43 — negated rise + shall/ought/may + bare no-worse/better
    PredScenario(
        "never_rises_flat_holds",
        "never rises",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 43: never rises is flat, not rise",
    ),
    PredScenario(
        "never_rises_helped_missed",
        "never rises",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: never rises was rise → invented held when score rose",
    ),
    PredScenario(
        "doesnt_rise_helped_missed",
        "doesn't rise",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="doesn't rise missed the rise-negation list (only does not rise)",
    ),
    PredScenario(
        "wont_improve_helped_missed",
        "won't improve",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="won't improve / cannot improve were still rise",
    ),
    PredScenario(
        "shall_not_fall_hurt_missed",
        "shall not fall",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=2,
        note="THE LIE: shall/ought/may not fall were fall → invented held on hurt",
    ),
    PredScenario(
        "ought_not_fall_flat_holds",
        "ought not to fall",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="ought not to fall → flat",
    ),
    PredScenario(
        "no_worse_hurt_missed",
        "no worse",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=2,
        note="THE LIE: bare no worse matched worse → fall → invented held on hurt",
    ),
    PredScenario(
        "no_better_helped_missed",
        "no better",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="bare no better matched better → rise → invented held on helped",
    ),
    PredScenario(
        "wont_get_worse_hurt_missed",
        "won't get worse",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=2,
        note="get worse under negation was still fall",
    ),
    # Slice 44 — trailing comparator percents
    PredScenario(
        "pct_higher_holds",
        "20% higher",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 44: 20% higher ≡ 20% of pop (Δ=+1 on pop 5)",
    ),
    PredScenario(
        "pct_higher_missed",
        "20% higher",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: trailing higher left pct=None → direction invented held on +20",
    ),
    PredScenario(
        "pct_lower_missed",
        "20% lower",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="20% lower unbound → direction invents held on absolute-sized fall",
    ),
    PredScenario(
        "pct_more_holds",
        "20% more",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="more/less bind intent from trailing comparator",
    ),
    PredScenario(
        "pct_more_missed",
        "20% more",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="20% more was unknown+unbound; now rise+percent misses abs",
    ),
    PredScenario(
        "pct_up_missed",
        "20% up",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="20% up had rise intent but no percent",
    ),
    # Slice 45 — bare up N / down N magnitude
    PredScenario(
        "up_n_holds",
        "up 1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 45: bare up 1 parses magnitude (up by 1 already did)",
    ),
    PredScenario(
        "up_n_missed",
        "up 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: up 1 left amount=None → direction invented held on +20",
    ),
    PredScenario(
        "down_n_missed",
        "down 1",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="down 1 unbound → direction invents held on absolute-sized fall",
    ),
    # Slice 46 — signed +N / -N intent
    PredScenario(
        "plus_one_holds",
        "+1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 46: bare +1 is rise + magnitude",
    ),
    PredScenario(
        "plus_one_missed",
        "+1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: +1 had amount but intent=unknown → no-direction",
    ),
    PredScenario(
        "minus_one_missed",
        "-1",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="bare -1 was no-direction; now fall+magnitude misses abs",
    ),
    PredScenario(
        "pass_rate_plus_one_missed",
        "pass rate +1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="word-boundary before + failed after space",
    ),
    # Slice 47 — crash/collapse/soar targets + from→to
    PredScenario(
        "crashes_to_zero_holds",
        "crashes to zero",
        "hurt",
        -3,
        5,
        "prediction-held",
        latest_value=0,
        note="Slice 47: crash/collapse open targets like falls to zero",
    ),
    PredScenario(
        "crashes_to_zero_missed",
        "crashes to zero",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=1,
        note="THE LIE: crashes unbound → no-direction; direction invents held off-zero",
    ),
    PredScenario(
        "soars_to_missed",
        "soars to 5/5",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="soar unbound → direction invents held at wrong latest",
    ),
    PredScenario(
        "from_to_holds",
        "from 3/5 to 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="from→to destination is the target",
    ),
    PredScenario(
        "from_to_missed",
        "from 3/5 to 4/5",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=5,
        note="wrong destination latest must miss",
    ),
    PredScenario(
        "arrow_to_missed",
        "3/5 → 4/5",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=3,
        note="arrow transition destination grades latest",
    ),
    # Slice 48 — arrow glyphs ↑1/↓1 + unbound perfect score
    PredScenario(
        "arrow_up_holds",
        "↑1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 48: ↑1 owns rise+magnitude",
    ),
    PredScenario(
        "arrow_up_missed",
        "↑1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: unbound ↑1 left no-direction; direction invents held on +20",
    ),
    PredScenario(
        "arrow_down_missed",
        "↓1",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="↓1 magnitude — direction invents held on absolute-sized drop",
    ),
    PredScenario(
        "arrow_frac_holds",
        "↑1/5",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="↑1/5 had amount but no intent; now grades",
    ),
    PredScenario(
        "perfect_score_holds",
        "perfect score",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="unbound perfect resolves to pop",
    ),
    PredScenario(
        "perfect_score_missed",
        "perfect score",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: unbound left no-direction; flat invents held off-perfect",
    ),
    # Slice 49 — climbs/slips · grows/shrinks · out-of · full marks · 100%
    PredScenario(
        "climbs_holds",
        "climbs 1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 49: climbs N owns magnitude",
    ),
    PredScenario(
        "climbs_missed",
        "climbs 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: amount=None invented held on Δ=+20",
    ),
    PredScenario(
        "slips_missed",
        "slips 1",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="slips N magnitude",
    ),
    PredScenario(
        "grows_missed",
        "grows by 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: amount on table but intent unknown → no-direction",
    ),
    PredScenario(
        "shrinks_holds",
        "shrinks by 1",
        "hurt",
        -1,
        5,
        "prediction-held",
        latest_value=3,
        note="shrinks is fall+magnitude",
    ),
    PredScenario(
        "out_of_holds",
        "5 out of 5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="N out of P is a target",
    ),
    PredScenario(
        "out_of_missed",
        "5 out of 5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: unbound left no-direction; flat invents held",
    ),
    PredScenario(
        "score_of_missed",
        "score of 5/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="score of N/N is a target",
    ),
    PredScenario(
        "full_marks_missed",
        "full marks",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="full marks resolves like perfect score",
    ),
    PredScenario(
        "hundred_pct_missed",
        "100%",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="bare 100% resolves to population",
    ),
    PredScenario(
        "tops_out_missed",
        "tops out at 5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="tops/maxes out at N is a target",
    ),
    PredScenario(
        "caps_at_missed",
        "caps at 5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=6,
        note="caps at N is a ceiling",
    ),
    # Slice 50 — fat arrows · word magnitudes · all green
    PredScenario(
        "fat_arrow_holds",
        "⬆1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 50: fat ⬆ owns rise+magnitude",
    ),
    PredScenario(
        "fat_arrow_missed",
        "⬆1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: fat arrow unbound left no-direction",
    ),
    PredScenario(
        "tri_arrow_missed",
        "▲1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="▲/▼ glyphs grade like ↑/↓",
    ),
    PredScenario(
        "word_one_holds",
        "up by one",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="word magnitude one ≡ 1",
    ),
    PredScenario(
        "word_one_missed",
        "up by one",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: amount=None invented held on Δ=+20",
    ),
    PredScenario(
        "one_point_missed",
        "rises one point",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="one point ≡ magnitude 1",
    ),
    PredScenario(
        "two_points_missed",
        "rises by two",
        "helped",
        1,
        5,
        "prediction-missed",
        latest_value=4,
        note="two ≡ 2; Δ=+1 must miss",
    ),
    PredScenario(
        "all_green_holds",
        "all green",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="all green resolves to population",
    ),
    PredScenario(
        "all_green_missed",
        "all green",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: unbound left no-direction; flat invents held",
    ),
    PredScenario(
        "all_passing_missed",
        "all passing",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="all passing / passes all are perfect→pop",
    ),
    # Slice 51 — gains/loses/plus/minus · bare a-point
    PredScenario(
        "gains_one_holds",
        "gains one",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 51: gains one ≡ magnitude 1",
    ),
    PredScenario(
        "gains_one_missed",
        "gains one",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: amount=None invented held on Δ=+20",
    ),
    PredScenario(
        "up_a_point_missed",
        "up a point",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: a point without by left amount=None",
    ),
    PredScenario(
        "gains_1_missed",
        "gains 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="gains N digit form",
    ),
    PredScenario(
        "loses_one_missed",
        "loses one",
        "hurt",
        -20,
        5,
        "prediction-missed",
        latest_value=0,
        note="THE LIE: loses one was fully unbound",
    ),
    PredScenario(
        "plus_1_missed",
        "plus 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="plus N owns rise+magnitude like +N",
    ),
    PredScenario(
        "minus_1_holds",
        "minus 1",
        "hurt",
        -1,
        5,
        "prediction-held",
        latest_value=3,
        note="minus N owns fall+magnitude",
    ),
    PredScenario(
        "adds_1_missed",
        "adds 1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="adds/subtracts grade magnitude",
    ),
    PredScenario(
        "subtracts_1_holds",
        "subtracts 1",
        "hurt",
        -1,
        5,
        "prediction-held",
        latest_value=3,
        note="subtracts is fall+magnitude",
    ),
    # Slice 52 — 100 percent · N of N · scores/still · green/failures
    PredScenario(
        "hundred_percent_word_missed",
        "100 percent",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: 100 percent unbound while 100% graded",
    ),
    PredScenario(
        "hundred_pct_word_holds",
        "100 pct",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="100 pct resolves to population",
    ),
    PredScenario(
        "n_of_n_missed",
        "5 of 5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: bare N of N unbound; out of graded",
    ),
    PredScenario(
        "scores_slash_missed",
        "scores 5/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="scores/gets/marks/still N/N are targets",
    ),
    PredScenario(
        "still_slash_holds",
        "still 5/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=5,
        note="still N/N grades latest",
    ),
    PredScenario(
        "remains_green_missed",
        "remains green",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="THE LIE: flat invents held without perfect resolve",
    ),
    PredScenario(
        "stays_green_missed",
        "stays green",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="stays/still green resolve to population",
    ),
    PredScenario(
        "zero_failures_missed",
        "zero failures",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="zero/no failures are perfect→pop",
    ),
    PredScenario(
        "all_tests_pass_missed",
        "all tests pass",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="all tests pass / everything passes",
    ),
    # Slice 53 — emoji FE0F arrows · double-struck · word-number percent
    PredScenario(
        "emoji_arrow_holds",
        "⬆️1",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 53: FE0F emoji arrow owns magnitude",
    ),
    PredScenario(
        "emoji_arrow_missed",
        "⬆️1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: FE0F blocked digit → amount=None invented held",
    ),
    PredScenario(
        "double_struck_missed",
        "⇑1",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="⇑/⇧/🔼 grade like ↑/⬆",
    ),
    PredScenario(
        "word_twenty_pct_missed",
        "twenty percent higher",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: word twenty left pct=None; invents held on Δ=+20",
    ),
    PredScenario(
        "word_twenty_pct_holds",
        "improves by twenty percent",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="twenty percent of pop 5 ≡ Δ+1",
    ),
    # Slice 54 — word from→to
    PredScenario(
        "word_from_to_holds",
        "from three to four",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 54: word destination grades latest",
    ),
    PredScenario(
        "word_from_to_missed",
        "from three to four",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: word from→to unbound left no-direction",
    ),
    PredScenario(
        "goes_from_word_missed",
        "goes from three to five",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="goes from WORD to WORD destination",
    ),
    PredScenario(
        "from_one_to_zero_missed",
        "from one to zero",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=1,
        note="word zero destination",
    ),
    # Slice 55 — bare word to / bare percent
    PredScenario(
        "bare_word_to_holds",
        "three to four",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 55: bare WORD to WORD (no from) grades latest",
    ),
    PredScenario(
        "bare_word_to_missed",
        "three to four",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: bare three to four unbound left no-direction",
    ),
    PredScenario(
        "goes_word_to_missed",
        "goes three to five",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=4,
        note="goes WORD to WORD without from",
    ),
    PredScenario(
        "bare_twenty_pct_holds",
        "twenty percent",
        "helped",
        1,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 55: bare twenty percent ≡ Δ+1 on pop 5",
    ),
    PredScenario(
        "bare_twenty_pct_missed",
        "twenty percent",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: bare twenty percent unbound → invents held on Δ=+20",
    ),
    PredScenario(
        "bare_digit_pct_missed",
        "20%",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: bare 20% unbound while +20% graded",
    ),
    PredScenario(
        "by_twenty_pct_missed",
        "by twenty percent",
        "helped",
        20,
        5,
        "prediction-missed",
        latest_value=24,
        note="THE LIE: pct parsed, intent unknown → no-direction",
    ),
    # Slice 56 — bare digit / slash / mixed to
    PredScenario(
        "bare_digit_to_holds",
        "3 to 4",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 56: bare digit to grades latest",
    ),
    PredScenario(
        "bare_digit_to_missed",
        "3 to 4",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: bare 3 to 4 unbound left no-direction",
    ),
    PredScenario(
        "bare_slash_to_missed",
        "3/5 to 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE: bare 3/5 to 4/5 unbound while from 3/5 to 4/5 graded",
    ),
    PredScenario(
        "goes_digit_to_missed",
        "goes 3 to 4",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=2,
        note="goes N to N without from",
    ),
    PredScenario(
        "mixed_to_missed",
        "3 to four",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: mixed digit/word unbound",
    ),
    # Slice 57 — decimal refuse · up to · down to
    PredScenario(
        "up_to_holds",
        "up to 4",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 57: up to N is a ceiling",
    ),
    PredScenario(
        "up_to_missed",
        "up to 4",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE: up to stole rise; ceiling unbound → invents held",
    ),
    PredScenario(
        "down_to_holds",
        "down to 2",
        "hurt",
        -2,
        5,
        "prediction-held",
        latest_value=2,
        note="Slice 57: down to N is a target",
    ),
    PredScenario(
        "down_to_missed",
        "down to 2",
        "hurt",
        -1,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: down to was fall with no target → invents held",
    ),
    PredScenario(
        "decimal_pct_refused",
        "2.5%",
        "helped",
        0,
        5,
        "no-direction",
        latest_value=3,
        note="THE LIE: 2.5% invented pct=5; now refuse rather than truncate",
    ),
    # Slice 58 — ordinals + equals
    PredScenario(
        "ordinal_digit_to_holds",
        "3rd to 4th",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 58: ordinal digit destination",
    ),
    PredScenario(
        "ordinal_digit_to_missed",
        "3rd to 4th",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: 3rd to 4th unbound left no-direction",
    ),
    PredScenario(
        "ordinal_word_to_missed",
        "third to fourth",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: third to fourth unbound while three to four graded",
    ),
    PredScenario(
        "ordinal_slash_to_missed",
        "3rd/5 to 4th/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=5,
        note="THE LIE: 3rd/5 to 4th/5 invented raw=5 to 4 (digit steal)",
    ),
    PredScenario(
        "equals_slash_holds",
        "equals 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 58: equals is a target like exactly",
    ),
    PredScenario(
        "equals_slash_missed",
        "equals 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: equals unbound while exactly graded — invents held",
    ),
    PredScenario(
        "equal_to_missed",
        "equal to 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=5,
        note="equal to synonym of equals",
    ),
    PredScenario(
        "eq_eq_missed",
        "== 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=2,
        note="== glyph equals target",
    ),
    PredScenario(
        "equals_word_missed",
        "equals four",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="equals four word destination",
    ),
    # Slice 59 — same-as invent-held + is/reads/matches
    PredScenario(
        "same_as_holds",
        "same as 4/5",
        "unchanged",
        0,
        5,
        "prediction-held",
        latest_value=4,
        note="Slice 59: same as is a target",
    ),
    PredScenario(
        "same_as_missed",
        "same as 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: same as 4/5 was flat+no target → invents held @3",
    ),
    PredScenario(
        "is_slash_missed",
        "is 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="THE LIE: is 4/5 unbound left no-direction",
    ),
    PredScenario(
        "reads_missed",
        "reads 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=2,
        note="reads N is a target readout",
    ),
    PredScenario(
        "matches_missed",
        "matches 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=5,
        note="matches N like equals",
    ),
    PredScenario(
        "lands_on_missed",
        "lands on 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="lands on vs lands at (already graded)",
    ),
    PredScenario(
        "finishes_at_missed",
        "finishes at 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="finishes at end-state",
    ),
    PredScenario(
        "comes_to_missed",
        "comes to 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="comes to destination",
    ),
    PredScenario(
        "identical_to_missed",
        "identical to 4/5",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="identical to synonym of same as",
    ),
    PredScenario(
        "eleventh_to_twelfth_missed",
        "eleventh to twelfth",
        "unchanged",
        0,
        20,
        "prediction-missed",
        latest_value=11,
        note="THE LIE: eleventh/twelfth unbound while 11th to 12th graded",
    ),
    PredScenario(
        "same_as_word_missed",
        "same as four",
        "unchanged",
        0,
        5,
        "prediction-missed",
        latest_value=3,
        note="same as four word destination",
    ),
)


def run_pred_demo() -> str:
    """Print magnet vs naive_direction on magnitude/level/floor/ceiling/target scenarios."""
    lines = [
        "MAGNET pred-demo — magnitude + stay-at + floor/ceiling/target honesty vs naive",
        "",
        "  When a prediction names a fraction (rises by 1/5), magnet checks Δ.",
        "  When it names a stay-at level (must stay at 5/5 or stay at 5), magnet checks latest.",
        "  When it names a floor (at least 4/5), magnet checks latest ≥ floor.",
        "  When it names a ceiling (at most 3/5), magnet checks latest ≤ ceiling.",
        "  When it names a target (falls to 2/5 / reaches 5/5 / exactly 4/5), magnet checks latest.",
        "  When it names a percent (improves by 20%), magnet checks Δ vs round(pop·pct/100).",
        "  When it names doubles/halves, magnet checks prior = latest − Δ (Slice 37).",
        "  When it names a below-bound (`won't fall below 3/5`), magnet opens the floor (Slice 38).",
        "  Percent works without `by` (`rises 20%`); triples/3x grade prior (Slice 39).",
        "  Word form `20 percent` / `20 pct` is percent-of-pop — never absolute (Slice 40).",
        "  never falls / cannot fall / won't decrease are flat — NOT fall (Slice 40).",
        "  never rises / doesn't rise / won't improve are flat — NOT rise (Slice 43).",
        "  shall/ought/may not fall + bare no worse/better are flat (Slice 43).",
        "  `20% higher` / `20% more` / `20% up` are percent-of-pop (Slice 44).",
        "  bare `up 1` / `down 1` grade magnitude (Slice 45).",
        "  bare `+1` / `-1` own rise/fall intent (Slice 46).",
        "  crashes/collapses/soars to N + from→to destinations are targets (Slice 47).",
        "  arrow glyphs `↑1` / `↓1` own rise/fall + magnitude (Slice 48).",
        "  unbound `perfect score` resolves to latest == population (Slice 48).",
        "  `climbs 1` / `slips 1` grade magnitude; grows/shrinks own intent (Slice 49).",
        "  `5 out of 5` / `score of N/N` / `full marks` / `100%` are targets (Slice 49).",
        "  fat arrows `⬆1`/`▲1` + word magnitudes `by one`/`one point` (Slice 50).",
        "  `all green` / `all passing` / `passes all` resolve to population (Slice 50).",
        "  `gains one` / `up a point` / `plus 1` / `loses one` grade magnitude (Slice 51).",
        "  `100 percent` / `5 of 5` / `scores 5/5` / `stays green` resolve (Slice 52).",
        "  emoji `⬆️1` / `⇑1` + word `twenty percent` grade (Slice 53).",
        "  word `from three to four` destinations are targets (Slice 54).",
        "  bare `three to four` + bare `twenty percent` / `20%` grade (Slice 55).",
        "  bare `3 to 4` / `3/5 to 4/5` / mixed `3 to four` grade (Slice 56).",
        "  decimal `2.5%` refused (not truncated to 5); `up to`/`down to` grade (Slice 57).",
        "  `falls to zero` / `goes to zero` / `perfect N/N` are targets (Slice 41).",
        "  quadrupples / N times / Nfold grade prior like Nx (Slice 41).",
        "  won't fall / does not regress are flat — NOT fall (Slice 35 negation honesty).",
        "  recover/restore/regain/rebound are rise (Slice 32 — Devpost one-workflow grades).",
        "  Naive grades direction only — invents held when the claim is wrong.",
        "",
        "  scenario                 claim                    Δ    pop  latest magnet              naive",
        "  " + "-" * 104,
    ]
    magnet_ok = 0
    naive_ok = 0
    embarrass = 0
    for sc in SCENARIOS:
        m = check_prediction(
            sc.prediction,
            sc.label,
            sc.delta,
            population=sc.population,
            latest_value=sc.latest_value,
        )
        n = naive_direction_check(
            sc.prediction,
            sc.label,
            sc.delta,
            population=sc.population,
            latest_value=sc.latest_value,
        )
        m_out = m["outcome"]
        n_out = n["outcome"]
        if m_out == sc.magnet_truth:
            magnet_ok += 1
        if n_out == sc.magnet_truth:
            naive_ok += 1
        if (
            sc.magnet_truth == "prediction-missed"
            and m_out == "prediction-missed"
            and n_out == "prediction-held"
        ):
            embarrass += 1
        level = claimed_level(sc.prediction)
        floor = claimed_floor(sc.prediction)
        ceiling = claimed_ceiling(sc.prediction)
        target = claimed_target(sc.prediction)
        pct = claimed_percent(sc.prediction)
        ratio = claimed_ratio(sc.prediction)
        claim = claimed_magnitude(sc.prediction)
        if ratio["kind"] is not None:
            claim_txt = ratio["kind"]
        elif pct["percent"] is not None:
            claim_txt = f"{pct['percent']}%"
        elif floor["value"] is not None:
            pop = floor["population"]
            op = ">" if floor.get("exclusive") else "≥"
            claim_txt = (
                f"{op}{floor['value']}/{pop}"
                if pop is not None
                else f"{op}{floor['value']}"
            )
        elif ceiling["value"] is not None:
            pop = ceiling["population"]
            claim_txt = (
                f"≤{ceiling['value']}/{pop}"
                if pop is not None
                else f"≤{ceiling['value']}"
            )
        elif target["value"] is not None:
            pop = target["population"]
            claim_txt = (
                f"to {target['value']}/{pop}"
                if pop is not None
                else f"to {target['value']}"
            )
        elif target.get("perfect"):
            claim_txt = "perfect→pop"
        elif level["value"] is not None:
            pop = level["population"]
            claim_txt = (
                f"stay {level['value']}/{pop}"
                if pop is not None
                else f"stay {level['value']}"
            )
        elif claim["amount"] is not None and claim["population"] is not None:
            claim_txt = f"{claim['amount']}/{claim['population']}"
        elif claim["amount"] is not None:
            claim_txt = str(claim["amount"])
        else:
            claim_txt = prediction_intent(sc.prediction)
        delta_txt = "—" if sc.delta is None else f"{sc.delta:+d}"
        pop_txt = "—" if sc.population is None else str(sc.population)
        latest_txt = "—" if sc.latest_value is None else str(sc.latest_value)
        lines.append(
            f"  {sc.name:<25}{claim_txt:<24}{delta_txt:<5}{pop_txt:<5}"
            f"{latest_txt:<7}{m_out:<20}{n_out}"
        )

    total = len(SCENARIOS)
    lines += [
        "",
        f"  magnet       {magnet_ok}/{total}  (bounds + percent + ratio when claimed)",
        f"  naive        {naive_ok}/{total}  (direction only — pre-Slice-25 behaviour)",
        f"  embarrassed  {embarrass} scenario(s) where naive invents held on wrong claim",
        "",
    ]
    if embarrass >= 1 and magnet_ok == total:
        lines.append(
            "  FINDING  naive direction-only invents prediction-held when the "
            "claimed fraction, bound (incl. below-bound floors), percent "
            "(incl. word form `20 percent` and `50% better`), or "
            "doubles/halves/triples/quadruples/N-times ratio is wrong; "
            "magnet misses. Open the measured Δ / latest / prior. "
            "`won't fall below N` opens the floor — never invent held beneath "
            "the named bound (Slice 38). `never falls` / `won't decrease` are "
            "flat — never invent held on a drop (Slice 40). `falls to zero` "
            "grades latest=0 — never invent held off-zero (Slice 41). "
            "`gains 20%` / `boosts by 20%` are rise+percent — not no-direction "
            "(Slice 42). `never rises` / `doesn't rise` / `won't improve` / "
            "`shall not fall` / bare `no worse` are flat — never invent held on "
            "a negated move (Slice 43). `20% higher` / `20% more` / `20% up` are "
            "percent-of-pop — never invent held on absolute Δ (Slice 44). "
            "bare `up 1` / `down 1` grade magnitude — never invent held on "
            "absolute Δ (Slice 45). bare `+1` / `-1` own rise/fall intent — "
            "never leave a claimable magnitude as no-direction (Slice 46). "
            "`crashes to zero` / `soars to N` / `from A to B` are targets — "
            "never invent held off the named destination (Slice 47). "
            "`↑1` / `↓1` own rise/fall + magnitude — never leave a glyph "
            "claim as no-direction (Slice 48). unbound `perfect score` "
            "resolves to population — never invent held off-perfect (Slice 48). "
            "`climbs 1` / `grows by 1` grade magnitude — never invent held on "
            "absolute Δ (Slice 49). `5 out of 5` / `full marks` / `100%` are "
            "targets — never invent held off the named level (Slice 49). "
            "`⬆1` / `▲1` / `up by one` / `one point` grade magnitude — never "
            "leave a word or fat-arrow claim as no-direction (Slice 50). "
            "`all green` / `all passing` resolve to population (Slice 50). "
            "`gains one` / `up a point` / `plus 1` / `loses one` grade "
            "magnitude — never invent held on absolute Δ (Slice 51). "
            "`100 percent` / `5 of 5` / `scores 5/5` / `remains green` / "
            "`stays green` / `zero failures` resolve to population or "
            "named level — never invent held off-perfect (Slice 52). "
            "`⬆️1` / `⇑1` grade magnitude through FE0F; `twenty percent "
            "higher` is percent-of-pop — never invent held on absolute Δ "
            "(Slice 53). word `from three to four` destinations grade "
            "latest — never invent held off the named end-state (Slice 54). "
            "bare `three to four` (no from) grades destination; bare "
            "`twenty percent` / `20%` / `by twenty percent` are "
            "percent-of-pop rise — never invent held on absolute Δ "
            "(Slice 55). bare `3 to 4` / `3/5 to 4/5` / mixed "
            "`3 to four` destinations grade latest — never invent held "
            "off the named end-state (Slice 56). decimal `2.5%` / "
            "`by 1.5` refuse truncation — never invent pct=5 or "
            "amount=1 from a fractional digit (Slice 57). `up to N` is "
            "a ceiling; `down to N` is a target — never invent held off "
            "the named bound (Slice 57). ordinal `3rd to 4th` / "
            "`third to fourth` destinations grade latest — never invent "
            "held off the named end-state or steal digits from "
            "`3rd/5 to 4th/5` (Slice 58). `equals 4/5` / `equal to` / "
            "`== 4/5` / `equals four` are targets like `exactly` — "
            "never invent held off the named level (Slice 58). "
            "`same as 4/5` grades latest — never invent held from bare "
            "flat `same` with no target (Slice 59). `is` / `reads` / "
            "`matches` / `lands on` / `finishes at` / `comes to` / "
            "`identical to` are targets; word ordinals `eleventh` / "
            "`twelfth` grade like digit `11th` / `12th` (Slice 59)."
        )
    elif magnet_ok < total:
        lines.append(
            f"  FINDING  magnet scored {magnet_ok}/{total} — bound grade drifted; "
            "re-check claimed_* / check_prediction."
        )
    else:
        lines.append(
            "  note  no claim-embarrassment scenario fired — unexpected."
        )
    lines += [
        "",
        "  repro      magnet pred-demo",
        "  repro      magnet adopt skill x 'pass rate rises by 2/5' --probe demo-pass-rate --demo-bonus --reset",
        "  repro      magnet adopt skill x 'must stay at 5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'at least 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'at most 3/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x \"won't fall\" --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'falls to 2/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'improves by 20%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'exactly 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'pass rate doubles' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x \"won't fall below 3/5\" --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'stays above 3/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'rises 20%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'pass rate triples' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'improves by 20 percent' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'never falls' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'falls to zero' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'perfect 5/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'pass rate quadruples' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '50% better' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'gains 20%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'never rises' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x \"shall not fall\" --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'no worse' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '20% higher' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '20% more' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'up 1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'down 1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '+1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '-1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'crashes to zero' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'from 3/5 to 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '↑1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '↓1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'perfect score' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'climbs 1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'grows by 1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '5 out of 5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'full marks' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '100%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '⬆1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'up by one' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'all green' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'gains one' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'up a point' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'plus 1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'loses one' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '100 percent' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '5 of 5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'scores 5/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'remains green' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '⬆️1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '⇑1' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'twenty percent higher' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'from three to four' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'three to four' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'twenty percent' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '20%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '3 to 4' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '3/5 to 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'up to 4' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'down to 2' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '2.5%' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '3rd to 4th' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'third to fourth' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'equals 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x '== 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'equals four' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'same as 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'is 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'reads 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'matches 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'lands on 4/5' --probe demo-pass-rate --reset",
        "  repro      magnet adopt skill x 'eleventh to twelfth' --probe demo-pass-rate --reset",
    ]
    return "\n".join(lines)
